import {
  Banknote, Home, Landmark, CreditCard, Stethoscope, TrendingUp,
  Baby, Palette, Hospital, Briefcase, FileText, Handshake,
  User, Users, Dumbbell, Building2, Gift, Glasses, GraduationCap,
  Target, Bot, Lock, PartyPopper, BarChart3, Link, Receipt,
  AlertTriangle, CheckCircle2, Key, MapPin, Sparkles, Building,
  ShoppingBag, Wallet, PiggyBank, HeartPulse, BookOpen, Star,
  Search, Zap, Compass, Newspaper, Megaphone, Info, Headphones,
  UserRound, ClipboardList, Bell, MessageCircle, Smartphone,
  IdCard, Hash, Leaf, CircleHelp, UsersRound, Droplets, Bath,
  School, Book, Backpack, Pill, Bed, Car, Lightbulb,
  ScanLine,
  type LucideIcon,
} from 'lucide-react'

const EMOJI_ICON_MAP: Record<string, LucideIcon> = {
  '💰': ShoppingBag,
  '🏠': Home,
  '🏡': Home,
  '🏦': Landmark,
  '💳': CreditCard,
  '🩺': Stethoscope,
  '📈': TrendingUp,
  '👶': Baby,
  '🎨': Palette,
  '🏥': Hospital,
  '💼': Briefcase,
  '📄': FileText,
  '💸': Banknote,
  '🤝': Handshake,
  '👵': User,
  '🥋': Dumbbell,
  '🏢': Building2,
  '🎁': Gift,
  '👓': Glasses,
  '🎓': GraduationCap,
  '🎯': Target,
  '🤖': Bot,
  '🔐': Lock,
  '🎉': PartyPopper,
  '📊': BarChart3,
  '🔗': Link,
  '🏛️': Building,
  '🧾': Receipt,
  '⚠️': AlertTriangle,
  '✅': CheckCircle2,
  '🔑': Key,
  '📌': MapPin,
  '✨': Sparkles,
  '👩‍👧': Users,
  '💵': Wallet,
  '🐷': PiggyBank,
  '❤️': HeartPulse,
  '📚': BookOpen,
  '⭐': Star,
  '🔍': Search,
  '⚡': Zap,
  '🧭': Compass,
  '📰': Newspaper,
  '📢': Megaphone,
  'ℹ️': Info,
  '🎧': Headphones,
  '👤': UserRound,
  '📋': ClipboardList,
  '🔔': Bell,
  '💬': MessageCircle,
  '📱': Smartphone,
  '🪪': IdCard,
  '🔢': Hash,
  '🌿': Leaf,
  '👨‍👩‍👧': UsersRound,
  '🧑‍🤝‍🧑': UsersRound,
  '💑': UsersRound,
  '👴': UserRound,
  '🙋': UserRound,
  '💧': Droplets,
  '🧴': Bath,
  '🏫': School,
  '📖': Book,
  '🎒': Backpack,
  '💊': Pill,
  '🏨': Bed,
  '🚗': Car,
  '🚨': AlertTriangle,
  '👧': Baby,
  '⛪': Building,
  '👩': UserRound,
  '🏙️': Building2,
  '🏧': CreditCard,
  '💡': Lightbulb,
  '🔒': Lock,
  '📝': FileText,
  '🟡': CircleHelp,
  '🟢': CircleHelp,
  '⊞': ScanLine,
}

interface EmojiProps {
  char: string
  size?: number
  color?: string
  style?: React.CSSProperties
}

export default function Emoji({ char, size = 22, color = 'var(--primary)', style }: EmojiProps) {
  const IconComponent = EMOJI_ICON_MAP[char]
  if (!IconComponent) return <CircleHelp size={size} color={color} strokeWidth={1.8} style={style} />
  return <IconComponent size={size} color={color} strokeWidth={1.8} style={style} />
}
